# Generated by Django 2.0.2 on 2018-05-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
